### PR TITLE
Adding some common part libraries to the Common Parts Library

### PR DESCRIPTION
**Pull request by FlyingLotus1983**

### CODE REVIEW

**Comment by skabashnyuk** [comment]
@swurzel  Any plans to merge this PR?

**Comment by sanketg10** [comment]
Hi @skabashnyuk, have merged it now, thanks!

**Comment by skabashnyuk** [comment]
@sanketg10 this pr is a bit old. Any plans to have official octopart  up to date Eagle library?

**Comment by sanketg10** [comment]
Hi @skabashnyuk, the latest Eagle library can be downloaded from SnapEDA: http://www.snapeda.com/libraries/octopart/common-parts-library/ - all the CPL parts are available to be downloaded in a single library. Hope it's useful!

**Comment by skabashnyuk** [comment]
So what is the purpose of CPL-Eagle-Library git repo?

**Comment by sanketg10** [comment]
The purpose of the git repo is so that users can send their own symbols and footprints for CPL parts. Since SnapEDA is our partner, we are re-directing the users to their website who keep the footprints updated and incorporate the users' feedback as it comes - and they support multiple PCB design tools as well. Would you find it more useful if that library was here?

**Pull request merged**
